### ISSUE TITLE
The form labels fly completely off the box

### ISSUE THREAD

**Issue by TekMonksGitHub** [mildrenben/surface#55]
On Chrome latest versions...

![image](https://user-images.githubusercontent.com/16070987/50686471-f122b800-1060-11e9-8869-b8db51eb3881.png)

**Comment by mrt-prodz** [comment]
I encountered the same issue and used this workaround, warning I'm still working on a project so cross-browser compatibility is not yet tested :
```css
input[type=email], input[type=text], input[type=password] {
	margin-top: 10px;
	margin-bottom: 10px;
}

input:placeholder-shown {
	padding-top: 1.2em;
}
```
On my end the placeholder was barely visible, just a couple pixels were showing up.
